---
title: "pilot"
author: "Timothy Lee"
date: "28/11/2020"
output: html_document
---

```{r}
library(leaflet)
library(geojsonio)
library(dplyr)
library(stringr)
library(ggplot2)
```

```{r echo=FALSE, message=FALSE}
# Map data
world_map <- geojsonio::geojson_read("https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json", what = "sp")
sg_map <- geojsonio::geojson_read("https://github.com/yinshanyang/singapore/raw/master/maps/0-country.geojson", what = "sp")
sg_map@data$name <- "Singapore"

#Countries data
countries_data <- readr::read_csv("https://github.com/timothyLeeXQ/Gender_representation_in_Legislatures/raw/main/API_SG.GEN.PARL.ZS_DS2_en_csv_v2_1740381.csv") %>% 
  select(.data$`Country Code`,
         .data$`Country Name`,
         paste(1997:2019)
         ) %>%
  tidyr::pivot_longer(.data,
                      cols = paste(1997:2019),
                      names_to = "year",
                      values_to = "proportion") %>%
  mutate(proportion = round(.data$proportion, digits = 2))


## Setup - Colouring for maps
map_bins <- c(0, 10, 20, 30, 40, 50)
pal <- colorBin("RdYlGn", domain = world_map@data$proportion, bins = map_bins)

  


# For slider filtering
countries_data_select <- countries_data %>% filter(year == "2000")



```


```{r}
#Map Data joining
world_map@data <- world_map@data %>%
  dplyr::left_join(countries_data_select, by = c("id" = "Country Code")) %>%
  select(-.data$name)

sg_map@data <- sg_map@data %>%
  dplyr::left_join(countries_data_select, by = c("name" = "Country Name"))

```


```{r}
# World Map Leaflet code

world_labels <- sprintf("<strong>%s</strong><br/>%g%%",
                        world_map@data$`Country Name`,
                        world_map@data$proportion) %>%
  lapply(htmltools::HTML)

leaflet_world <- leaflet(options = leafletOptions(minZoom = 2, maxZoom = 3)) %>%
  setView(lat = 0, lng = 60, zoom = 2) %>%
  setMaxBounds(lat1 = 90,
               lat2 = -90,
               lng1 = -179.739113,
               lng2 = 179.739113) %>%
  addTiles(attribution = "<a href = 'https://data.worldbank.org/indicator/SG.GEN.PARL.ZS'>Data from the World Bank</a>") %>%
  addPolygons(data = world_map, stroke = TRUE, smoothFactor = 0.5,
              weight = 1, color = '#333333', opacity = 1, 
              fillColor = ~pal(proportion), 
              fillOpacity = 1,
              highlightOptions = highlightOptions(color = '#000000',
                                                  weight = 3,
                                                  bringToFront = TRUE,
                                                  sendToBack = TRUE),
              label = world_labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")
              ) %>%
  addLegend("bottomright",
            pal = pal,
            values = world_map@data$proportion,
            opacity = 1,
            title = htmltools::HTML("% Women<br>in Legislature"))
```


```{r}
leaflet_world
```


```{r}

# SG Map Leaflet code

sg_labels <- sprintf("<strong>%s</strong><br/>%g%%",
                     sg_map@data$`name`,
                     sg_map@data$proportion) %>%
  lapply(htmltools::HTML)


leaflet_map_sg <- leaflet(options = leafletOptions(minZoom = 11, maxZoom = 11)) %>%
  setView(lat = 1.352754, lng = 103.866692, zoom = 11) %>%
  setMaxBounds(lat1 = 1.157170,
               lat2 = 1.476471,
               lng1 = 103.588712,
               lng2 = 104.1) %>%
  addPolygons(data = sg_map, stroke = TRUE, smoothFactor = 0.5,
              weight = 1, color = '#333333', opacity = 1, 
              fillColor = ~pal(proportion), 
              fillOpacity = 1,
              highlightOptions = highlightOptions(color = '#000000',
                                                  weight = 3,
                                                  bringToFront = TRUE,
                                                  sendToBack = TRUE),
              label = sg_labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")
              )

leaflet::renderLeaflet()
```



```{r}
leaflet_map_sg
```



```{r}
countries_data %>%
  filter(str_detect(.data$`Country Name`, pattern = regex("Singapore|Malaysia"))) %>%
ggplot(aes(x = year, y = proportion, group = `Country Name`, col = `Country Name`)) +
  geom_line() +
  theme_minimal()

```


```{r message = FALSE}
SG_Parl_women <- readr::read_csv("SG_Parl_women.csv") %>%
  pivot_longer(cols = -.data$Year,
               names_to = "position",
               values_to = "proportion")
```


```{r}
ggplot(SG_Parl_women, aes(x = .data$Year, y = .data$proportion, .data$position, col = .data$position)) +
  geom_line(size = 1) +
  scale_x_continuous(breaks = c(2009, 2011, 2013, 2015, 2017, 2019),
                     limits = c(2009, 2020)) +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5),
                     limits = c(0, 0.5),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0.5, linetype = "dashed", size = 1) +
  geom_hline(yintercept = 0.3, linetype = "dashed", size = 1) +
  annotate("text", x = 2009, y = .53, label = "Parity", hjust = 0) +
  annotate("text", x = 2009, y = .33, label = "UN 30% Guideline", hjust = 0) +
  labs(x = "\nYear",
       y = "Proportion of Women\n",
       col = "% Females as...") +
  theme_minimal() +
  theme(axis.title.x = element_text(size = 14, family = "TT Arial"),
        axis.title.y = element_text(size = 14, family = "TT Arial"),
        axis.text = element_text(size = 12, family = "TT Arial"),
        axis.text.x = element_text(angle = 45, hjust = 1))
```












